using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pentagon_Numbers
{
    class Program
    {
        //Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
               //1, 5, 12, 22, 35, 51, 70, 92, 117, 145, 
        //It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
        //Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
        static void Main(string[] args)
        {
            // Pn = n(3n - 1)/2
            bool loop = true;
            int result = 0;
            int i = 1;
            while (loop)
            {

                int x = i * ((3 * i) - 1) / 2;
                i++;
                for (int j = i - 1; j > 0; j--)
                {
                    int y = j * ((3 * j) - 1) / 2;
                    if (IsPentagon(x - y) && IsPentagon(x + y))
                    {
                        result = (x - y);
                        Console.WriteLine(result.ToString());
                        loop = false;
                        break;
                    }
                }




            }
            Console.ReadLine();
        }

        public static bool IsPentagon(int num)
        {
            double isthatpent = (Math.Sqrt(24 * num + 1) + 1) / 6;
            //  (math.sqrt(24*x + 1) + 1)/6 = Bir x sayısı eğer pentagon ise belirtilen işlem daima doğal sayı çıkar
            return isthatpent == (int)isthatpent;

        }
    }
}
